version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: mysite
    ports:
      - '80:80'
    restart: unless-stopped
    volumes:
      - /Users/pavelprosvetov/nginx/index.html:/usr/share/nginx/html/index.html
      - /Users/pavelprosvetov/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - site

networks:
  site:
    name: site
    driver: bridge
    
